name: IOUMC
version: '1.0.1'
main: iou.ink.iOUMC.IOUMC
api-version: '1.20'
commands:
  test:
    description: Test command
    usage: /<command>  #  命令return false时给出的提示
    aliases: ["test1"]  # 命令的别名